########################################################################
# Settings for Core Archive Connector
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
########################################################################

## Docker image of the Core Archive Connector
## ------------------------------------------

image:
   ## Specifies the root folder within the Docker registry
   source:

   ## Specifies the image name
   name: otacc
   tag: 

   ## imagePullPolicy (see https://kubernetes.io/docs/concepts/containers/images/)
   # pullPolicy: Always

## -----------------------------------------------------------------------
## Important: The following values are only consumed during "helm install"
## During "helm upgrade" the values are ignored by the Connector.
## -----------------------------------------------------------------------

## Core Archive and Business Administrator
## ---------------------------------------

cloud:
   ## Specifies the URL to Core Archive
   url:

   ## Specifies the name of the Business Administrator
   baUser:

   ## Contains the Base64-encoded password of the Business Administrator
   baPassword:

   ## Allow insecure server connections when using SSL
   ## For productive Core Archive servers there is no need to set this flag
   insecure: false

## Connector internal settings
## ---------------------------

connector:
   ## Contains the Base64-encoded password of the internal
   ## Core Archive Connector user. This is a password of a technical user
   ## used internally by the Core Archive Connector.
   ## This password can later be changed in the Business Administration
   ## webclient under Settings -> Password
   password:

   ## The following format is supported by the httpsProxy variable
   ## http://<proxyHost>:<proxyPort>
   ## http://<proxyUser>:<proxyPassword>@<proxyHost>:<proxyPort>
   httpsProxy:

   ## Specifies the hostname of the container
   ## If this parameter is not set the hostname is generated by Kubernetes
   # hostname: otacc

   ## If the connector is already registered in Core Archive and this
   ## connector needs a reregistration, then set this value to true
   reregister: false

   ## Following log levels are supported: Warn, Info, Debug, Trace
   loglevel: Info

   ## Use a HTTP proxy
   useProxy: false

## Container related settings
## --------------------------

## serviceName defines the name of the Kubernetes service for otacc
serviceName: otacc

## port defines the internal port of the Kubernetes service for otacc
port: 8080

## serviceAccountName defines the name of the service account the
## pods are running under. Normally that is 'default'
serviceAccountName: default

## readinessProbe indicates if the Core Archive Connector pod is
## ready to receive traffic.
readinessProbe:
  enabled: true

  ## After failing failureThreshold times, pod won't receive any further data.
  failureThreshold: 3

  ## The probe is repeated every periodSeconds.
  periodSeconds: 30

  ## Probes are started initialDelaySeconds after pod inital start.
  initialDelaySeconds: 25

  ## Count as failed probe if probe doesn't return after timeoutSeconds.
  timeoutSeconds: 6

## livenessProbe indicates if the Core Archive Connector pod is
## still alive and operational.
livenessProbe:
  enabled: true

  ## After failing failureThreshold times pod gets restarted.
  failureThreshold: 3

  ## The probe is repeated every periodSeconds.
  periodSeconds: 30

  ## Probes are started initialDelaySeconds after pod inital start.
  initialDelaySeconds: 0

  ## Count as failed probe if probe doesn't return after timeoutSeconds.
  timeoutSeconds: 6

## resources.* defines the resource requirements for Core Archive Connector
resources:
  enabled: true
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi
  ## logStorage defines the storage size for the logs volume
  logStorage: 5Gi
  ## storageClassName defines the Kubernetes storage class for persistent volumes
  storageClassName: standard

## existingSecret: An already existing kubernetes secret, which contains passwords.
## If this is specified then the kubernetes secret will be preferred, and any provided password values will be ignored.
# existingSecret: secretname
