{{- if not .Values.existingSecret }}
########################################################################
# OpenText PowerDocs Database Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.password | b64enc }}
---
{{- end }}