apiVersion: v1
kind: Secret
metadata:
  name: migrate-job-secrets
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD: {{ .Values.otdsdb.password | b64enc }}
{{- if and .Values.migration.enabled (not .Values.migration.usingLegacyImage) }}
  OTDS_DIRECTORY_BOOTSTRAP_PASSWORD: {{ .Values.migration.password | b64enc }}
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: {{ .Values.cryptKey | b64enc }}  
{{- end }}
---
