{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-connector-password
data:
  CONNECTOR_PASSWORD: {{ required "A valid connector.password is required!" .Values.connector.password | b64enc }}
type: Opaque
{{- end }}
