apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
     app: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  ports:
  - name: "{{ .Values.port }}"
    port: {{ required "A valid port is required!" .Values.port }}
    targetPort: 8080
  selector:
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
