{{- if not .Values.existingSecret }}
########################################################################
# OpenText Archive Center Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTDS_PASS: {{ .Values.otds.password | b64enc }}
  TARGET_DB_PASSWORD: {{ .Values.database.password | b64enc }}
  PG_PASSWORD: {{ .Values.database.adminPassword | b64enc }}
---
{{- end }}
