{{- if not .Values.global.otdsMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: otiv-delete-lock-secrets
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    helm.sh/chart: {{ include "brava.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: otiv-delete-lock-secrets
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "brava.name" . }}
        helm.sh/chart: {{ include "brava.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      serviceAccountName: otiv-asecret-sa
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
      containers:
      - name: delete-lock-secrets
        image: {{ include "otds.init.image.path" . }}
        securityContext:
          allowPrivilegeEscalation: false
        command:
          - bash
        args: [ "-c",
                "sleep 1;
                 output=`kubectl delete secrets otiv-resourcel-lock otiv-metis-lock otiv-highlight-lock otiv-publication-lock otiv-publisher-lock`;
                 if [ \"$?\" -eq \"0\" ];
                 then
                     echo \"Secrets deleted; Continuing.\";
                 else
                     echo \"Secrets didn't exist; Continuing.\";
                 fi;" ]
{{- end }}
