{{- if not .Values.global.otdsMigration }}
{{- if not .Values.otcs }} # using OTCS secrets instead
apiVersion: v1
kind: Secret
metadata:
  name: otiv-base-secrets
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    helm.sh/chart: {{ include "brava.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.global.dbSecretKey }}: {{ .Values.global.database.adminPassword | b64enc | quote }}
  otdsPassword: {{ .Values.global.masterPassword | b64enc }}
{{- end }}

{{- if .Values.global.usingServiceMesh }}
---
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otiv-resource-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: otiv-resource-secret
type: Opaque
data:
{{- if $secret }}
  name: {{ $secret.data.name }}
  resource: {{ $secret.data.resource }}
{{- else }}
  name: {{ "iv" | b64enc }}
  resource: {{ "initialization:ResourceString" | b64enc | b64enc }}
{{- end }}

---
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otiv-highlight-secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: otiv-highlight-secrets
type: Opaque
data:
{{- if $secret }}
  authId: {{ $secret.data.authId }}
  authSecret: {{ $secret.data.authSecret }}
{{- else }}
  authId: {{ "iv-highlight" | b64enc }}
  authSecret: {{ "initializationSecret" | b64enc }}
{{- end }}

---
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otiv-metis-secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: otiv-metis-secrets
type: Opaque
data:
{{- if $secret }}
  authId: {{ $secret.data.authId }}
  authSecret: {{ $secret.data.authSecret }}
{{- else }}
  authId: {{ "iv-metis" | b64enc }}
  authSecret: {{ "initializationSecret" | b64enc }}
{{- end }}

---
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otiv-publication-secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: otiv-publication-secrets
type: Opaque
data:
{{- if $secret }}
  authId: {{ $secret.data.authId }}
  authSecret: {{ $secret.data.authSecret }}
{{- else }}
  authId: {{ "iv-publication" | b64enc }}
  authSecret: {{ "initializationSecret" | b64enc }}
{{- end }}

---
{{- $secret := lookup "v1" "Secret" .Release.Namespace "otiv-publisher-secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: otiv-publisher-secrets
type: Opaque
data:
{{- if $secret }}
  authId: {{ $secret.data.authId }}
  authSecret: {{ $secret.data.authSecret }}
{{- else }}
  authId: {{ "iv-publisher" | b64enc }}
  authSecret: {{ "initializationSecret" | b64enc }}
{{- end }}

{{- end }}
{{- end }}
