{{- if not .Values.existingSecret }}
########################################################################
# OpenText Content Server Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
{{- if (regexFind "\\/|'|\\\\" .Values.passwords.adminPassword)  }}
  {{- fail "Passwords cannot contain the following symbols: \\ / ' " }}
{{- else if (regexFind "\\/|'|\\\\" .Values.passwords.database.adminPassword)  }}
  {{- fail "Admin database passwords cannot contain the following symbols: \\ / '" }}
{{- else if (regexFind "\\/|'|\\\\" .Values.passwords.database.password)  }}
  {{- fail "Database passwords cannot contain the following symbols: \\ / '" }}
{{- else }}
  # Environment variable format is kept for use by the otiv helm chart
  ADMIN_USER_PASSWORD: {{ .Values.passwords.adminPassword | b64enc }}
  DATA_ENCRYPTION_KEY: {{ .Values.passwords.dataEncryptionKey | b64enc }}
  DB_ADMIN_PASSWORD: {{ .Values.passwords.database.adminPassword | b64enc }}
  DB_PASSWORD: {{ .Values.passwords.database.password | b64enc }}
  {{- if eq .Values.config.documentStorage.type "otacc" }}
  AC_CORE_PASSWORD: {{ .Values.passwords.otacc.corePassword | required "A valid .Values.passwords.otacc.corePassword value is required" | b64enc }}
  {{- end }}
  {{- if eq .Values.config.createBizadminUser true }}
  BIZ_ADMIN_PASSWORD: {{ .Values.passwords.baPassword | required "A valid .Values.passwords.baPassword value is required" | b64enc }}
    {{- if (regexFind "\\/|'|\\\\" .Values.passwords.baPassword)  }}
    {{- fail "bizadmin passwords cannot contain the following symbols: \\ / '" }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.config.createAppMonitorUser true }}
  APPMONITOR_PASSWORD: {{ .Values.passwords.appMonitorPassword | required "A valid .Values.passwords.appMonitorPassword value is required" | b64enc }}
    {{- if (regexFind "\\/|'|\\\\" .Values.passwords.appMonitorPassword)  }}
    {{- fail "appmonitor password cannot contain the following symbols: \\ / '" }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.config.deployBusinessScenarios true }}
  SCENARIO_OWNER_PASSWORD: {{ .Values.passwords.scenarioOwnerPassword | required "A valid .Values.passwords.scenarioOwnerPassword value is required" | b64enc }}
    {{- if (regexFind "\\/|'|\\\\" .Values.passwords.scenarioOwnerPassword)  }}
    {{- fail "scenarioOwner passwords cannot contain the following symbols: \\ / '" }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
