apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "base.resource.name" . }}-configmap
data:
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    DB_PROVIDER: postgresql
    DB_HOST: {{ .Values.global.database.hostname }}
    DB_PORT: '{{ .Values.global.database.port }}'
    DB_NAME: {{ default .Values.global.database.ivName .Values.database.name }}
    DB_PSQL: {{ .Values.global.database.adminDatabase }}
    DB_USER: {{ .Values.global.database.adminUsername }}
    DB_USE_SSL: '{{ .Values.global.database.ssl }}'
    DB_MAX_POOL_SIZE: '{{ .Values.dbMaxPoolSize }}'
{{- if .Values.enableRoleBasedAccessControl }}
    ENABLE_ROLE_BASED_ACCESS_CONTROL: '{{ .Values.enableRoleBasedAccessControl }}'
{{- end }}
{{- if .Values.jwtSecret }}
    MARKUP_JWT_SECRET: '{{ .Values.jwtSecret }}'
{{- end }}
    LOG_LEVEL: '{{ .Values.loglevel }}'
    {{- template "new.relic.viewing.config" . }}
    MARKUP_AUTHORITY: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn" . }}
    NODE_ENV: production
{{- if .Values.nodeOptions }}
    NODE_OPTIONS: '{{ .Values.nodeOptions }}'
{{- end }}
    OTDS_CERT_UPDATE_INTERVAL: '{{ .Values.global.otdsCertUpdateInterval }}'
    OTDS_ORIGIN: {{ template "otds.api.url" .}}
    PORT: '{{ .Values.service.targetPort }}'
    {{- template "proxy.url.params" . }}
    {{- template "timezone" . }}
    __VERSION__: '{{ template "version.stamp" . }}'
