########################################################################
# OpenText Archive Center Database Kubernetes Service
{{- if eq .Values.enableLoadBalancer true }}
# Exposed outside the kubernetes cluster via a LoadBalancer
{{- else }}
# Not exposed outside the kubernetes cluster.
{{- end }}
########################################################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
spec:
{{- if eq .Values.enableLoadBalancer true }}
  type: LoadBalancer
{{- end }}
  ports:
  - name: {{ .Chart.Name }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
