apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "base.resource.name" . }}-configmap
data:
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    DOC_ROOT: http://developer.opentext.com
    DISABLE_FORWARDING: '{{ .Values.disableForwarding }}'
    LOG_LEVEL: '{{ .Values.loglevel }}'
    {{- template "new.relic.viewing.config" . }}
{{- if .Values.nodeOptions }}
    NODE_OPTIONS: '{{ .Values.nodeOptions }}'
{{- end }}
    OTDS_CERT_UPDATE_INTERVAL: '{{ .Values.global.otdsCertUpdateInterval }}'
    OTDS_ORIGIN: {{ template "otds.api.url" .}}
    PORT: '{{ .Values.service.targetPort }}'
    {{- template "timezone" . }}
    VIEWER_AUTHORITY: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn" .}}
    __VERSION__: '{{ template "version.stamp" . }}'
