{{- if not .Values.existingSecret }}
########################################################################
# OpenText PowerDocs Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTPD_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc }}
  OTPD_USER_PASSWORD: {{ .Values.userPassword | b64enc }}
  OTPD_MONITOR_USER_PASSWORD: {{ .Values.monitorUserPassword | b64enc }}
  OTPD_API_USER_PASSWORD: {{ .Values.apiUserPassword | b64enc }}
  OTDS_PASSWORD: {{ .Values.otds.password | b64enc }}
  OTCS_ADMIN_PASSWORD: {{ .Values.otcs.password | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.adminPassword | b64enc }}
  POSTGRES_PD_PASSWORD: {{ .Values.database.password | b64enc }}
---
{{- end }}