# Service Account required for the pre-upgrade job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otxecm-pre-upgrade-job-sa
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

---
# RBAC role to be assigned to service account for the pre-upgrade job
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otxecm-pre-upgrade-job-role
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["", "apps"]
  resources: ["services", "statefulsets"]
  verbs: ["list", "delete"]

---
# Binding the role with the service account for the pre-upgrade job
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otxecm-pre-upgrade-job-rbac
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otxecm-pre-upgrade-job-role
subjects:
- kind: ServiceAccount
  name: otxecm-pre-upgrade-job-sa

---
# Pre-upgrade job definition
apiVersion: batch/v1
kind: Job
metadata:
  name: otxecm-pre-upgrade-job
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      serviceAccountName: otxecm-pre-upgrade-job-sa
      containers:
      - name:  otxecm-pre-upgrade-container
        {{- $imageTag := include "pre.upgrade.job.image.tag" . -}}
{{- if not (regexFind "\\/$" .Values.preUpgradeJob.image.source ) }}
        image: {{ .Values.preUpgradeJob.image.source }}/{{ .Values.preUpgradeJob.image.name }}:{{ $imageTag }}
{{- else }}
        image: {{ .Values.preUpgradeJob.image.source }}{{ .Values.preUpgradeJob.image.name }}:{{ $imageTag }}
{{- end }}
        command: ["sh"]
        args:
          - "-c"
          - "kubectl delete statefulsets.apps --all && kubectl delete services --ignore-not-found=true otcs-backend-search"

---
