{{- if not .Values.existingSecret }}
########################################################################
# OpenText Content Server Database Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
{{- if (regexFind "\\/|'|\\\\" .Values.password)  }}
  {{- fail "Passwords cannot contain the following symbols: \\ / ' " }}

{{- else }}

  DB_ADMIN_PASSWORD: {{ .Values.password | b64enc }}

{{- end }}
---

{{- end }}
